### ISSUE TITLE
Doc example about the private_key_jwt does not work

### ISSUE THREAD

**Issue by violette** [Connect2id/Server-Issues#10]
Hi,
I followed the doc example for registering a new client using private_key_jwt at https://connect2id.com/products/server/docs/guides/client-registration#private-key-jwt and it does not work:

`{"error_description":"Invalid client metadata field jwks \/ jwks_uri: JWK set contains private key(s)","error":"invalid_client_metadata"}`

**Comment by c2id-support** [comment]
Hi,

The Connect2id server detected that a private key was leaked in the registered JWK set, which is dangerous for security. Please, remove the private key parameters, and try again.

**Comment by violette** [comment]
Indeed, I was just testing and c/p it badly from the generator. Thank you ;)
