### ISSUE TITLE
Authz Store: revocation API documentation incorrect

### ISSUE THREAD

**Issue by RCanine** [Connect2id/Server-Issues#2]
The docs for [authz revocation](http://connect2id.com/products/server/docs/integration/authz-store#revocation) are labeled as POST, but the example is DELETE, and the examples in the docs for revoking all of a subjects authentications appear to not work:

```
POST {{c2id}}/authz-store/rest/v2/revocation?subject={{sub}}&client_id={{client_id}}
Authorization: Bearer {{token}}
Content-Type: application/json
{}
```

Returns an HTTP Status 415 - Unsupported Media Type error.

C2ID version: 3.1.1

**Comment by c2id-support** [comment]
Thanks for submitting this. The docs are fixed now:

http://connect2id.com/products/server/docs/integration/authz-store#revocation-post

In v2 of the authz store API the revocation call is modelled after RFC 7009 which uses form encoding. We've got a ticket to add support for application/json as well.
