### ISSUE TITLE
3.3a release requires "preset_claims" 

### ISSUE THREAD

**Issue by pakfur** [Connect2id/Server-Issues#3]
FYI: current release fails on auth step with this error:

Bad request: Missing JSON object member with key "preset_claims"

see:
https://gist.github.com/pakfur/676520ac946e014d07c4

This is not a blocker for us yet, just an FYI

**Comment by c2id-support** [comment]
Thanks.

Including an empty preset_claims JSON object should provide a temp work around 
this.

**Comment by c2id-support** [comment]
This a subsequent snapshot that should have this issue fixed:

https://connect2id.com/assets/products/server/download/3.3-132-1/c2id.war

Way may provide with other significant snapshots as work on 3.3 continues.
