### ISSUE TITLE
Invalid enum property: Property: authzStore.ldapServer.selectionAlgorithm: Value: ROUND-ROBIN

### ISSUE THREAD

**Issue by pakfur** [Connect2id/Server-Issues#4]
I am setting the following CATALINA_OPTS value:
app_1     | CATALINA_OPTS LOADED:  -Djgroups.tcp.address=10.180.243.79 -Djava.rmi.server.hostname=ip-10-180-243-79.rso.riotgames.com -Dcom.sun.management.jmxremote.rmi.port=9002 -Djgroups.tcp.port=7800 -Djgroups.fd_sock.start_port=7900 -Djgroups.s3.bucket=s3ping-c2id-prod  -Dop.reg.alwaysRefreshClientSecretOnUpdate=false -Dop.authz.alwaysPromptForConsent=true -DauthzStore.ldapServer.url="ldap://10.180.243.20:1389 ldap://10.180.243.106:1389" -Dop.reg.ldapServer.url="ldap://10.180.243.20:1389 ldap://10.180.243.106:1389" -DauthzStore.ldapDirectory.baseDN=ou=ath,o=rso -Dop.ldapClaimsSource.directory.baseDN=ou=ppl,o=rso -Dop.reg.ldapDirectory.baseDN=ou=clt,o=rso -Dop.issuer=http://auth.accounts.riotgames.com -Dop.authz.endpoint=http://auth.accounts.riotgames.com/authorize -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.net.preferIPv4Stack=true -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

Relevant error:

app_1     | 2015-07-27T21:55:02,420 FATAL localhost-startStop-1 MAIN - [AS0402] Couldn't load authorization store configuration: Invalid enum property: Property: authzStore.ldapServer.selectionAlgorithm: Value: ROUND-ROBIN
app_1     | com.nimbusds.common.config.ConfigurationException: Invalid enum property: Property: authzStore.ldapServer.selectionAlgorithm: Value: ROUND-ROBIN
app_1     | 	at com.nimbusds.authzstore.Configuration.<init>(Configuration.java:991) ~[Configuration.class:3.0.4]
app_1     | 	at com.nimbusds.authzstore.rest.Launcher.contextInitialized(Launcher.java:125) [Launcher.class:3.0.4]
app_1     | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4751) [catalina.jar:8.0.11]
app_1     | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5175) [catalina.jar:8.0.11]
app_1     | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.11]
app_1     | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724) [catalina.jar:8.0.11]
app_1     | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700) [catalina.jar:8.0.11]
app_1     | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.11]
app_1     | 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919) [catalina.jar:8.0.11]
app_1     | 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1704) [catalina.jar:8.0.11]
app_1     | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
app_1     | 	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
app_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_65]
app_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_65]
app_1     | 	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

**Comment by c2id-support** [comment]
Hello,

The value should be `ROUND_ROBIN` -- /underscore instead of dash/.

**Comment by pakfur** [comment]
FYI: It is wrong in the .properties file attribute desc.

**Comment by c2id-support** [comment]
Thanks and apologies!

**Comment by c2id-support** [comment]
The doc bug is confirmed. Will be fixed in the next server release. Thanks for reporting this.

**Comment by c2id-support** [comment]
Fixed in [3.3](http://www.connect2id.com/blog/connect2id-server-3.3). Happy coding!
