### ISSUE TITLE
preferred_client_secret always fails with  "The preferred secret must be at least 256 bits"

### ISSUE THREAD

**Issue by pakfur** [Connect2id/Server-Issues#5]
Trying to set the secret gives me this error, regardless of the preferred client secret length.

[jkline@JKLIN1ML1 bin (master *)]$ python create.py -v -h internal-rso-c2id-prod-1211360975.us-east-1.elb.amazonaws.com -c rso-sample-client -t ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6 -s pFETsq6yEhgFLXZhuAPUZ{Q3B2RNW7
Setting preferred client secret
sending metadata:
{
    "application_type": "web",
    "client_name": "RSO Sample Client",
    "contacts": [
        "rso_sample_client_admin@riotgames.com"
    ],
    "grant_types": [
        "refresh_token",
        "authorization_code"
    ],
    "post_logout_redirect_uris": [
        "https://rso-demo.i.leagueoflegends.com/oauth/logout-callback",
        "https://local.leagueoflegends.com:3000/oauth/logout-callback"
    ],
    "preferred_client_id": "rso-sample-client",
    "preferred_client_secret": "pFETsq6yEhgFLXZhuAPUZ{Q3B2RNW7",
    "redirect_uris": [
        "https://rso-sample.i.leagueoflegends.com/oauth2-callback",
        "https://local.leagueoflegends.com:3000/oauth2-callback"
    ]
}
register new client rso-sample-client
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): internal-rso-c2id-prod-1211360975.us-east-1.elb.amazonaws.com
send: 'POST /c2id/client-reg HTTP/1.1\r\nHost: internal-rso-c2id-prod-1211360975.us-east-1.elb.amazonaws.com\r\nContent-Length: 575\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json\r\nUser-Agent: python-requests/2.7.0 CPython/2.7.10 Darwin/14.4.0\r\nConnection: keep-alive\r\nContent-Type: application/json\r\nAuthorization: Bearer ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6\r\n\r\n{"redirect_uris": ["https://rso-sample.i.leagueoflegends.com/oauth2-callback", "https://local.leagueoflegends.com:3000/oauth2-callback"], "contacts": ["rso_sample_client_admin@riotgames.com"], "application_type": "web", "client_name": "RSO Sample Client", "grant_types": ["refresh_token", "authorization_code"], "preferred_client_secret": "pFETsq6yEhgFLXZhuAPUZ{Q3B2RNW7", "post_logout_redirect_uris": ["https://rso-demo.i.leagueoflegends.com/oauth/logout-callback", "https://local.leagueoflegends.com:3000/oauth/logout-callback"], "preferred_client_id": "rso-sample-client"}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: cache-control: no-store
header: Content-Type: application/json;charset=UTF-8
header: Date: Tue, 28 Jul 2015 02:24:23 GMT
header: pragma: no-cache
header: Server: Apache-Coyote/1.1
header: Content-Length: 135
header: Connection: keep-alive
DEBUG:requests.packages.urllib3.connectionpool:"POST /c2id/client-reg HTTP/1.1" 400 135
Error registering client rso-sample-client | Status 400 {"error":"invalid_client_metadata","error_description":"Invalid client metadata field: The preferred secret must be at least 256 bits"}

**Comment by c2id-support** [comment]
Hello,

Assuming that you're trying to use this feature - http://connect2id.com/products/server/docs/guides/client-registration#set-client-id :

The `pFETsq6yEhgFLXZhuAPUZ{Q3B2RNW7` secret is 31 symbols, which is 248 bits. 

The input secret should be at least 32 symbols (32 x 8 = 256). Otherwise the secret will be not accepted.

**Comment by pakfur** [comment]
You are correct. I miscalculated. Sorry for the confusion.

**Comment by c2id-support** [comment]
:)

**Comment by pakfur** [comment]
redacted personal info from the original comment.
