### ISSUE TITLE
Session token does not expire

### ISSUE THREAD

**Issue by pakfur** [Connect2id/Server-Issues#6]
We noticed the session lifetime does not appear to time out (we tested up to 30 minutes).

We set op.authz.sessionLifetime to 900 but the session does not time out.

This is for version 3.1.1 of the c2id server.

**Comment by c2id-support** [comment]
Apparently there's a bug in the docs, the time unit should be minutes, not seconds.

**Comment by c2id-support** [comment]
The time unit is correct now, the inline docs in /WEB-INF/oidcProvider.properties were also updated (for the next release - 3.4). Apologies for the error.

http://connect2id.com/products/server/docs/config/core#op-authz-sessionLifetime
