### ISSUE TITLE
GET /clients/ with non-existing client ID responds with 401 Unauthorized

### ISSUE THREAD

**Issue by RCanine** [Connect2id/Server-Issues#7]
Using C2ID 3.1.1:

```
curl -v \
  -H "Authorization: Bearer [token]" \
  -H "Content-Type: application/json" \
  'http://www.example.com/c2id/clients/thisclientdoesnotexist'
```

**Expected:**

```
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Connection: keep-alive
```

**Actual:**

```
< HTTP/1.1 401 Unauthorized
< www-authenticate: Bearer error="invalid_token", error_description="Invalid access token"
< Content-Length: 0
< Connection: keep-alive
```

Repeating the same request with a valid client correctly returns a 200 OK.

**Comment by c2id-support** [comment]
Thanks for reporting this, we'll check our test and try to reproduce it.

**Comment by c2id-support** [comment]
Hello,

The client reg spec mandates 401 Unauthorized when the client_id is invalid:

http://tools.ietf.org/html/rfc7592#section-2.1

We may relax this and return 404 in case you're using the master (admin) token to do the client GET, i.e. the client is not reading its own data. Please let us know if this can help your use case.

**Comment by c2id-support** [comment]
The next Connect2id server release (3.5) will return 404 on an invalid client_id if the master (admin) access token is used to GET / PUT / DELETE a client registration.

**Comment by c2id-support** [comment]
The 3.5 release is available for download now:

http://connect2id.com/blog/connect2id-server-3.5

The client registry API docs were updated accordingly:

http://connect2id.com/products/server/docs/api/client-registration#clients-id-get
