### ISSUE TITLE
Starting with connect2ID issue

### ISSUE THREAD

**Issue by fahmibedoui** [Connect2id/Server-Issues#9]
I'm beginner with connect2id. I have started by downloading the server and trying to test the demo of client "oidc-client" in local (http://127.0.0.1:8080/oidc-client/). The ldap server is normally up (launched as described in the README file). Unfortunately after clicking on "Authorize client" we end with a warning "Unexpected OpenID Connect authentication response" and the result is not completed. we figured out that the problem is caused by the host name. it works for 127.0.0.1 but not with other domain names.
It will be nice if you provide me with some explanations. And Is there more documentations or forum for these kind of questions as we want to use connect2id in our products?

**Comment by c2id-support** [comment]
Hi,

After the user is logged in and provided consent the Connect2id server
generates an [OpenID authentication response](http://openid.net/specs/openid-connect-core-1_0.html#AuthResponse).

This response is sent back to the client via HTTP 302 redirect to a
callback URI.

The Connect2id server (and most OAuth servers) require this callback to
be recorded in the [client registration](http://connect2id.com/products/server/docs/api/client-registration).
The demo client has this redirect_uri set to
http://127.0.0.1:8080/oidc-client/cb

If you invoke the client from http://localhost, the redirection will
proceed to http://127.0.0.1. However, there will be no session cookie on
127.0.0.1 to link the original request from http://localhost , and the
request will fail with "Unexpected authentication response".


If you want to install the OpenID Connect client on a different host,
make sure the client registration is updated to include the new
redirect_uri , or simply register a new client.

You can find more info on registering clients here:

The web API for registering and managing clients:

http://connect2id.com/products/server/docs/api/client-registration

The client registration howto:

http://connect2id.com/products/server/docs/guides/client-registration



If you want to use non-localhost for the Connect2id server itself, check
out this guide:

http://connect2id.com/products/server/docs/guides/non-localhost-evaluation
